# example netlify.toml
[build]
  command = "ng build"
  functions = "./functions"
  publish = "dist/netlify-angular17/browser"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  [dev]
    command = "ng build"
    functions = "./functions"
    publish = "src"

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
